# Generated by Django 5.0.1 on 2024-01-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='is_login',
            new_name='is_logged_in',
        ),
    ]
